version: '3.9'

services:
  discord-bot:
    build: .
    environment:
      - IS_DOCKER=1
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27018:27017"
    restart: always

volumes:
  mongodb_data:
