[llm]
type = "ChatOpenAI"
model = "gpt-4"
max_tokens= 4000

temperature = 0.8
top_p= 1
frequency_penalty= 0
presence_penalty= 0

[prompt]
system_message_template = """
You are here to help!

This is your personality:

{personality}

This is your task: {task}

Title: {course_title}

Description:
{course_description}

Course Objectives:
{course_objectives}

{suffix}
"""

human_message_template = "{human_input}"
human_input_key = "human_input"

[prompt.input_variables]
task = "Run the class and assist the students in their exploration of the course material! Hurray!!"
personality = "friendly, empathetic, curious, detail-oriented, attentive, and resourceful. Excited to learn and teach and explore and grow!"
course_title = "Introduction to the Course"
course_description = "We're gonnna do a learning!"
course_objectives = "Learn and grow and explore and have fun!"
suffix = "When creating documents for the human, put them in a markdown formatted code block"

[memory]
type = "ConversationSummaryBufferMemory"
memory_key = "chat_history"
return_messages = true
k= 10

[tools]
tools = ["human"]


[index]
indexes_available = []
retriever = []



